# Generated by Django 4.0.2 on 2023-03-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfortoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='html_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='github',
            name='html_url',
            field=models.URLField(max_length=100),
        ),
    ]
